
export const attributeList = [
  {
    label: '单次',
    value: 'single',
  }, {
    label: '周期',
    value: 'period',
  }];
export const policyList = [
  {
    label: '每时',
    value: 'hour',
  }, {
    label: '每天',
    value: 'day',
  }, {
    label: '每周',
    value: 'week',
  }, {
    label: '每月',
    value: 'month',
  }];
export const weekList = [
  {
    label: '星期一',
    value: 1,
  }, {
    label: '星期二',
    value: 2,
  }, {
    label: '星期三',
    value: 3,
  }, {
    label: '星期四',
    value: 4,
  }, {
    label: '星期五',
    value: 5,
  }, {
    label: '星期六',
    value: 6,
  }, {
    label: '星期日',
    value: 0,
  }];
export const timezoneList = [
  { name: '(UTC-12:00) 国际日期变更线西', id: 'Etc/GMT+12' },
  { name: '(UTC-11:00) 协调世界时-11', id: 'Etc/GMT+11' },
  { name: '(UTC-10:00) 夏威夷', id: 'Pacific/Honolulu' },
  { name: '(UTC-09:00) 安克雷奇', id: 'America/Anchorage' },
  { name: '(UTC-08:00) 下加利福尼亚州', id: 'America/Santa_Isabel' },
  { name: '(UTC-08:00) 太平洋时间（美国和加拿大）', id: 'America/Los_Angeles' },
  { name: '(UTC-07:00) 奇瓦瓦,拉巴斯,马萨特兰', id: 'America/Chihuahua' },
  { name: '(UTC-07:00) 亚利桑那', id: 'America/Phoenix' },
  { name: '(UTC-07:00) 山地时间（美国和加拿大）', id: 'America/Denver' },
  { name: '(UTC-06:00) 中美洲', id: 'America/Guatemala' },
  { name: '(UTC-06:00) 中部时间（美国和加拿大）', id: 'America/Chicago' },
  { name: '(UTC-06:00) 萨斯喀彻温', id: 'America/Regina' },
  { name: '(UTC-06:00) 瓜达拉哈拉,墨西哥城,蒙特雷', id: 'America/Mexico_City' },
  { name: '(UTC-05:00) 波哥大,利马,基多', id: 'America/Bogota' },
  { name: '(UTC-05:00) 印地安那州（东部）', id: 'America/Indiana/Indianapolis' },
  { name: '(UTC-05:00) 东部时间（美国和加拿大）', id: 'America/New_York' },
  { name: '(UTC-04:30) 加拉加斯', id: 'America/Caracas' },
  { name: '(UTC-04:00) 大西洋时间（加拿大）', id: 'America/Halifax' },
  { name: '(UTC-04:00) 亚松森', id: 'America/Asuncion' },
  { name: '(UTC-04:00) 乔治敦,拉巴斯,马瑙斯,圣胡安', id: 'America/La_Paz' },
  { name: '(UTC-04:00) 库亚巴', id: 'America/Cuiaba' },
  { name: '(UTC-04:00) 圣地亚哥', id: 'America/Santiago' },
  { name: '(UTC-03:30) 纽芬兰', id: 'America/St_Johns' },
  { name: '(UTC-03:00) 巴西利亚', id: 'America/Sao_Paulo' },
  { name: '(UTC-03:00) 格陵兰', id: 'America/Godthab' },
  { name: '(UTC-03:00) 卡宴,福塔雷萨', id: 'America/Cayenne' },
  { name: '(UTC-03:00) 布宜诺斯艾利斯', id: 'America/Argentina/Buenos_Aires' },
  { name: '(UTC-03:00) 蒙得维的亚', id: 'America/Montevideo' },
  { name: '(UTC-02:00) 协调世界时-2', id: 'Etc/GMT+2' },
  { name: '(UTC-01:00) 佛得角群岛', id: 'Atlantic/Cape_Verde' },
  { name: '(UTC-01:00) 亚速尔群岛', id: 'Atlantic/Azores' },
  { name: '(UTC+00:00) 卡萨布兰卡', id: 'Africa/Casablanca' },
  { name: '(UTC+00:00) 蒙罗维亚,雷克雅未克', id: 'Atlantic/Reykjavik' },
  { name: '(UTC+00:00) 都柏林,爱丁堡,里斯本,伦敦', id: 'Europe/London' },
  { name: '(UTC+00:00) 协调世界时', id: 'Etc/GMT' },
  { name: '(UTC+01:00) 阿姆斯特丹,柏林,伯尔尼,罗马,斯德哥尔摩,维也纳', id: 'Europe/Berlin' },
  { name: '(UTC+01:00) 布鲁塞尔,哥本哈根,马德里,巴黎', id: 'Europe/Paris' },
  { name: '(UTC+01:00) 中非西部', id: 'Africa/Lagos' },
  { name: '(UTC+01:00) 贝尔格莱德,布拉迪斯拉发,布达佩斯,卢布尔雅那,布拉格', id: 'Europe/Budapes' },
  { name: '(UTC+01:00) 萨拉热窝,斯科普里,华沙,萨格勒布', id: 'Europe/Warsaw' },
  { name: '(UTC+01:00) 温得和克', id: 'Africa/Windhoek' },
  { name: '(UTC+02:00) 雅典,布加勒斯特,伊斯坦布尔', id: 'Europe/Istanbul' },
  { name: '(UTC+02:00) 赫尔辛基,基辅,里加,索非亚,塔林,维尔纽斯', id: 'Europe/Kiev' },
  { name: '(UTC+02:00) 开罗', id: 'Africa/Cairo' },
  { name: '(UTC+02:00) 大马士革', id: 'Asia/Damascus' },
  { name: '(UTC+02:00) 安曼', id: 'Asia/Amman' },
  { name: '(UTC+02:00) 哈拉雷,比勒陀利亚', id: 'Africa/Johannesburg' },
  { name: '(UTC+02:00) 耶路撒冷', id: 'Asia/Jerusalem' },
  { name: '(UTC+02:00) 贝鲁特', id: 'Asia/Beirut' },
  { name: '(UTC+03:00) 巴格达', id: 'Asia/Baghdad' },
  { name: '(UTC+03:00) 明斯克', id: 'Europe/Minsk' },
  { name: '(UTC+03:00) 利雅得', id: 'Asia/Riyadh' },
  { name: '(UTC+03:00) 内罗毕', id: 'Africa/Nairobi' },
  { name: '(UTC+03:30) 德黑兰', id: 'Asia/Tehran' },
  { name: '(UTC+04:00) 莫斯科,圣彼得堡,伏尔加格勒', id: 'Europe/Moscow' },
  { name: '(UTC+04:00) 第比利斯', id: 'Asia/Tbilisi' },
  { name: '(UTC+04:00) 埃里温', id: 'Asia/Yerevan' },
  { name: '(UTC+04:00) 阿布扎比,马斯喀特', id: 'Asia/Dubai' },
  { name: '(UTC+04:00) 巴库', id: 'Asia/Baku' },
  { name: '(UTC+04:00) 路易港', id: 'Indian/Mauritius' },
  { name: '(UTC+04:30) 喀布尔', id: 'Asia/Kabul' },
  { name: '(UTC+05:00) 塔什干', id: 'Asia/Tashkent' },
  { name: '(UTC+05:00) 伊斯兰堡,卡拉奇', id: 'Asia/Karachi' },
  { name: '(UTC+05:30) 斯里加亚渥登普拉', id: 'Asia/Colombo' },
  { name: '(UTC+05:30) 钦奈,加尔各答,孟买,新德里', id: 'Asia/Kolkata' },
  { name: '(UTC+05:45) 加德满都', id: 'Asia/Kathmandu' },
  { name: '(UTC+06:00) 阿斯塔纳', id: 'Asia/Almaty' },
  { name: '(UTC+06:00) 达卡', id: 'Asia/Dhaka' },
  { name: '(UTC+06:00) 叶卡捷琳堡', id: 'Asia/Yekaterinburg' },
  { name: '(UTC+06:30) 仰光', id: 'Asia/Yangon' },
  { name: '(UTC+07:00) 曼谷,河内,雅加达', id: 'Asia/Bangkok' },
  { name: '(UTC+07:00) 新西伯利亚', id: 'Asia/Novosibirsk' },
  { name: '(UTC+08:00) 克拉斯诺亚尔斯克', id: 'Asia/Krasnoyarsk' },
  { name: '(UTC+08:00) 乌兰巴托', id: 'Asia/Ulaanbaatar' },
  { name: '(UTC+08:00) 北京,重庆,香港,乌鲁木齐', id: 'Asia/Shanghai' },
  { name: '(UTC+08:00) 佩思', id: 'Australia/Perth' },
  { name: '(UTC+08:00) 吉隆坡,新加坡', id: 'Asia/Singapore' },
  { name: '(UTC+08:00) 台北', id: 'Asia/Taipei' },
  { name: '(UTC+09:00) 伊尔库茨克', id: 'Asia/Irkutsk' },
  { name: '(UTC+09:00) 首尔', id: 'Asia/Seoul' },
  { name: '(UTC+09:00) 大阪,札幌,东京', id: 'Asia/Tokyo' },
  { name: '(UTC+09:30) 达尔文', id: 'Australia/Darwin' },
  { name: '(UTC+09:30) 阿德莱德', id: 'Australia/Adelaide' },
  { name: '(UTC+10:00) 霍巴特', id: 'Australia/Hobart' },
  { name: '(UTC+10:00) 雅库茨克', id: 'Asia/Yakutsk' },
  { name: '(UTC+10:00) 布里斯班', id: 'Australia/Brisbane' },
  { name: '(UTC+10:00) 关岛,莫尔兹比港', id: 'Pacific/Port_Moresby' },
  { name: '(UTC+10:00) 堪培拉,墨尔本,悉尼', id: 'Australia/Sydney' },
  { name: '(UTC+11:00) 符拉迪沃斯托克', id: 'Asia/Vladivostok' },
  { name: '(UTC+11:00) 所罗门群岛,新喀里多尼亚', id: 'Pacific/Guadalcanal' },
  { name: '(UTC+12:00) 协调世界时+12', id: 'Etc/GMT-12' },
  { name: '(UTC+12:00) 斐济,马绍尔群岛', id: 'Pacific/Fiji' },
  { name: '(UTC+12:00) 马加丹', id: 'Asia/Magadan' },
  { name: '(UTC+12:00) 奥克兰,惠灵顿', id: 'Pacific/Auckland' },
  { name: '(UTC+13:00) 努库阿洛法', id: 'Pacific/Tongatapu' },
  { name: '(UTC+13:00) 萨摩亚群岛', id: 'Pacific/Apia' },
];
